nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['content-type', 'authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
