App\Entity\Secret:
    attributes:
        hash:
            groups: ['secret']
        secretText:
            groups: ['secret']
        createdAt:
            groups: ['secret']
        expiresAt:
            groups: ['secret']
        remainingViews:
            groups: ['secret']